name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTAINER_GITHUB_TOKEN: ${{ secrets.CONTAINER_GITHUB_TOKEN }}
      CONTAINER_GITHUB_USERNAME: ${{ github.actor }}
      CONTAINER_TAILSCALE_KEY: ${{ secrets.CONTAINER_TAILSCALE_KEY }}
      CONTAINER_USER: ${{ vars.CONTAINER_USER }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Set up GPG for Git signing
        run: |
          echo "$GPG_PRIVATE_KEY" > gpg.key
      - name: Create .git-credentials file
        run: |
          echo "https://$CONTAINER_GITHUB_USERNAME:$CONTAINER_GITHUB_TOKEN@github.com" >> .git-credentials
      - name: Create .env file
        run: |
          cp env.example .env
          echo "GITHUB_TOKEN=$CONTAINER_GITHUB_TOKEN" >> .env
          echo "TAILSCALE_KEY=$CONTAINER_TAILSCALE_KEY" >> .env
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ github.actor }}/dev:latest
          cache-from: type=registry,ref=${{ github.actor }}/dev:latest
          cache-to: type=inline
          build-args: |
            USER=${{ vars.CONTAINER_USER }}
