name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTAINER_GITHUB_TOKEN: ${{ secrets.CONTAINER_GITHUB_TOKEN }}
      CONTAINER_GITHUB_USERNAME: ${{ github.actor }}
      CONTAINER_TAILSCALE_KEY: ${{ secrets.CONTAINER_TAILSCALE_KEY }}
      CONTAINER_USER: ${{ vars.CONTAINER_USER }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    steps:
      - uses: actions/checkout@v4
      - name: Create .git-credentials file
        run: |
          echo "https://$CONTAINER_GITHUB_USERNAME:$CONTAINER_GITHUB_TOKEN@github.com" >> .git-credentials
      - name: Create .env file
        run: |
          cp env.example .env
          echo "TAILSCALE_KEY=CONTAINER_TAILSCALE_KEY" >> .env
      - name: Build
        run: >
          docker build -t $CONTAINER_GITHUB_USERNAME/dev:latest \
            --build-arg GITHUB_USERNAME=$CONTAINER_GITHUB_USERNAME \
            --build-arg USER=$CONTAINER_USER \
            .
      - name: Tag
        run: docker tag $CONTAINER_GITHUB_USERNAME/dev:latest $DOCKER_REGISTRY_URL/$CONTAINER_GITHUB_USERNAME/dev
      - name: Login
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY
      - name: Push
        run: docker push $DOCKER_REGISTRY/$CONTAINER_GITHUB_USERNAME/dev:latest
