name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GPG for Git signing
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg.key
      - name: Create .git-credentials file
        run: |
          echo "https://${{ github.actor }}:${{ secrets.CONTAINER_GITHUB_TOKEN }}@github.com" >> .git-credentials
      - name: Create .env file
        run: |
          cp env.example .env
          echo "GITHUB_TOKEN=${{ secrets.CONTAINER_GITHUB_TOKEN }}" >> .env
          echo "TAILSCALE_KEY=${{ secrets.CONTAINER_TAILSCALE_KEY }}" >> .env
      - name: Build
        run: >
          docker build -t ${{ github.actor }}/dev:latest --build-arg USER=${{ vars.CONTAINER_USER }} .
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          hostname: bswinnerton-build-dev-${{ github.run_id }}
          tags: tag:ci
          version: latest
      - name: Tag
        run: docker tag ${{ github.actor }}/dev:latest ${{ vars.DOCKER_REGISTRY_URL }}/${{ github.actor }}/dev
      - name: Login
        run: docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ vars.DOCKER_REGISTRY_URL }}
      - name: Push
        run: docker push ${{ vars.DOCKER_REGISTRY_URL }}/${{ github.actor }}/dev:latest
